default_language_version:
    # force all unspecified python hooks to run python3
    python: python3.13

#ci:
#  autofix_prs: false

# all to match default
default_stages: [commit-msg, post-checkout, post-commit, post-merge, post-rewrite, pre-commit, pre-merge-commit, pre-push, pre-rebase, prepare-commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.8.2'
    hooks:
      - id: ruff
        args: [., --fix, --exit-non-zero-on-fix]
        pass_filenames: false
        stages: [manual, commit-msg, post-checkout, post-commit, post-merge, post-rewrite, pre-commit, pre-merge-commit, pre-push, pre-rebase, prepare-commit-msg]
      - id: ruff-format
        args: ["xonsh", "xontrib", "tests", "xompletions"]
        pass_filenames: false
        stages: [manual, commit-msg, post-checkout, post-commit, post-merge, post-rewrite, pre-commit, pre-merge-commit, pre-push, pre-rebase, prepare-commit-msg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - types-ujson
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              docs/_static/.+
          )$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
